### ISSUE TITLE
Readme.md links need to be updated

### ISSUE THREAD

**Issue by Kromster80** [debenu/DelphiZXingQRCode#5]
Due to Google.Code closure, the link :

https://code.google.com/p/zxing/

is now pointing to the same page linked below it:

https://github.com/zxing/zxing

Solution: Remove first link (https://code.google.com/p/zxing)

**Comment by rowanhanna** [comment]
Thank you, the link has been removed.

**Comment by Kromster80** [comment]
Thank you!
